name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build_release
    runs-on: windows-latest
    strategy:
      matrix:
        device:
          - akershus
          - ayn-odin
          - beryllium
          - cheeseburger
          - dipper-old
          - dipper
          - draco
          - dumpling
          - enchilada
          - equuleus
          - fajita
          - judyln
          - judyp
          - judypn
          - m1882
          - m1892
          - nx616j
          - olympic
          - pafm00
          - pd1821
          - perseus
          - polaris
          - sdm845-generic
          - skr-a0
          - star2qltechn
          - trident
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract certificate
        shell: pwsh
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
        run: Set-Content -Path ..\drivers.pfx -Value ([Convert]::FromBase64String($env:CERTIFICATE)) -AsByteStream
      - name: Package device ${{ matrix.device }}
        shell: pwsh
        env:
          PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: .\extract.ps1 -CodeName ${{ matrix.device }} -Certificate ..\drivers.pfx -Password $env:PASSWORD
      - name: Create ZIP package
        shell: pwsh
        run: Compress-Archive -Path ".\output\*" -DestinationPath ${{ matrix.device }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.device }}.zip
